
name: mi_primer_github_action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2  
    - name: Saludar
      run: echo Hola cuando hace push!
    - name: docker
      run: docker -v
    - name: build image
      run: docker build . -t cinthyamontalvo/gitactnodeimage:240520
    - name: list image
      run: docker images
    - name: pushing to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
      run: |
        echo: 'Docker login'
        docker login -u $DOCKER_USER -P $DOCKER_PASS
        echo: 'Sending to hub'
        docker push cinthyamontalvo/gitactnodeimage:240520
